<table class="table table-bordered table-sm table-hover table-fixed table-striped display" id="tblCRUD" cellspacing="0" style="width: 100%;">
	<thead>
		<tr>
			<th>Código</th>
			<th>Digito&nbsp;Verificación</th>
			<th>Tipo&nbsp;Documento</th>
			<th>Código&nbsp;Barras</th>
			<th>Nombre</th>
			<th>Razon&nbsp;Social</th>
			<th>Nombre&nbsp;Comercial</th>
			<th>Primer&nbsp;Nombre</th>
			<th>Segundo&nbsp;Nombre</th>
			<th>Primer&nbsp;Apellido</th>
			<th>Segundo&nbsp;Apellido</th>
			<th>EMail</th>
			<th>EMail2</th>
			<th>Celular</th>
			<th>Estado&nbsp;Civil</th>
			<th>Sexo</th>
			<th>No&nbsp;Tarjeta</th>
			<th>Dirección&nbsp;Residencia</th>
			<th>Ciudad&nbsp;Residencia</th>
			<th>Nombre&nbsp;Residencia</th>
			<th>Barrio</th>
			<th>Nombre&nbsp;Barrio</th>
			<th>Dpto</th>
			<th>Nombre&nbsp;Departamento</th>
			<th>País</th>
			<th>Nombre&nbsp;País</th>
			<th>Zona</th>
			<th>Nombre&nbsp;Zona</th>
			<th>Télefonos</th>
			<th>Dirección&nbsp;Correspondencia</th>
			<th>Ciudad&nbsp;C</th>
			<th>Nombre&nbsp;Ciudad&nbsp;C</th>
			<th>Barrio&nbsp;C</th>
			<th>Nombre&nbsp;Barrio&nbsp;C</th>
			<th>Dptop&nbsp;C</th>
			<th>Nombre&nbsp;Dptop&nbsp;C</th>
			<th>País&nbsp;C</th>
			<th>Nombre&nbsp;País&nbsp;C</th>
			<th>Télefonos&nbsp;C</th>
			<th>Fecha&nbsp;Nacimiento</th>
			<th>Ciudad&nbsp;Nacim</th>
			<th>Nombre&nbsp;Ciudad&nbsp;Nacim</th>
			<th>Profesión</th>
			<th>Nombre&nbsp;Profesión</th>
			<th>Ocupación</th>
			<th>Vendedor</th>
			<th>Nombre&nbsp;Vendendor</th>
			<th>Hijos</th>
			<th>Autoriza&nbsp;Uso&nbsp;Información</th>
			<th>Empresa&nbsp;Donde&nbsp;Labora</th>
			<th>Dirección&nbsp;Empresa</th>
			<th>Télefonos&nbsp;Empresa</th>
			<th>Ciudad&nbsp;Empresa</th>
			<th>Nombre&nbsp;Ciudad&nbsp;Empresa</th>
			<th>Barrio&nbsp;Empresa</th>
			<th>Nombre&nbsp;Barrio&nbsp;Empresa</th>
			<th>Dpto&nbsp;Empresa</th>
			<th>País&nbsp;Empresa</th>
			<th>Nombre&nbsp;País&nbsp;Empresa</th>
			<th>Cargo</th>
			<th>Nombre&nbsp;Cargo</th>
			<th>Contacto</th>
			<th>Tipo&nbsp;Contacto</th>
			<th>Sector</th>
			<th>Nombre&nbsp;Sector</th>
			<th>Fecha&nbsp;Creación</th>
			<th>Régimen</th>
			<th>Nombre&nbsp;Régimen&nbsp;Contributivo</th>
			<th>Tipo&nbsp;Cartera</th>
			<th>Nombre&nbsp;Tipo&nbsp;Cartera</th>
			<th>Cupo&nbsp;Crédito</th>
			<th>Dias&nbsp;Crédito</th>
			<th>Actividad&nbsp;Económica</th>
			<th>Nombre&nbsp;Actividad&nbsp;Económica</th>
			<th>Tarifa&nbsp;ICA</th>
			<th>Tarifa&nbsp;Retención&nbsp;IVA</th>
			<th>Tarifa&nbsp;Retefuente</th>
			<th>Retefuente&nbsp;Sobre&nbsp;Base</th>
			<th>Tipo&nbsp;Tercero</th>
			<th>Nombre&nbsp;Tipo&nbsp;Tercero</th>
			<th>Bloqueo&nbsp;por&nbsp;Monto</th>
			<th>Bloqueo&nbsp;por&nbsp;Vencimiento</th>
			<th>Aplicar&nbsp;Bloqueo&nbsp;a&nbsp;Pedidos</th>
			<th>Clasificación</th>
			<th>Nombre&nbsp;Clasificación</th>
			<th>Lista&nbsp;de&nbsp;Precios</th>
			<th>Almacén</th>
			<th>Nombre&nbsp;Almacén</th>
			<th>NO&nbsp;Liquidar&nbsp;IVA</th>
			<th>Responsabilidades&nbsp;Fiscales</th>
			<th>Estado</th>
		</tr>
	</thead>
	<tbody>
	</tbody>
</table>

<script type="text/javascript">
	$TITULO = '<?= $titulo ?>';
</script>